@startuml
hide empty description


[*] -right-> 创建申请单 : 提交申请单信息

state 创建申请单 {
    [*] --> 创建申请单本单
    创建申请单本单 --> 创建结算单
    创建结算单 --> 创建佐证文件
    创建佐证文件 --> [*]
}

创建申请单 -right->  [*] : 申请单创建完成

@enduml