@startuml
hide empty description
skinparam state {
  BackgroundColor LightCyan
}
'申请单业务校验
state 纳税人校验 {
    state 人员是否签署合同 <<choice>>

    T入口 <<EntryPoint>> --> 人员是否签署合同 : 查询企业人员
    人员是否签署合同 --> 纳税人校验失败 : 未与企业签署合同
    人员是否签署合同 --> 纳税人校验成功 : 已与企业签署合同
    纳税人校验成功 --> T成功出口 <<ExitPoint>>
    纳税人校验失败 --> T失败出口 <<ExitPoint>>
}
[*] --> T入口

state 佐证充分性校验 {
    state 是否提交业务明细 <<choice>>
    state 业务明细配置是否必填 <<choice>>
    state 是否提交佐证文件 <<choice>>
    state 佐证文件是否必须 <<choice>>
    
    E入口 <<EntryPoint>> --> 是否提交业务明细
    是否提交业务明细 --> 业务明细配置是否必填 : 未提交业务明细
    是否提交业务明细 --> 是否提交佐证文件 : 已提交业务明细
    业务明细配置是否必填 -right-> 是否提交佐证文件 : 业务明细非必填
    业务明细配置是否必填 --> 佐证不充分 : 业务明细必填
    是否提交佐证文件 -right-> 佐证充分 : 已提交佐证文件
    是否提交佐证文件 --> 佐证文件是否必须 : 未提交佐证文件
    佐证文件是否必须 -right-> 佐证充分 : 佐证文件不必须（TSP）
    佐证文件是否必须 --> 佐证不充分 : 佐证文件必须
    佐证不充分 --> E失败出口 <<ExitPoint>>
    佐证充分 --> E成功出口 <<ExitPoint>>
}

T成功出口 --> E入口

T失败出口 --> [*]
E失败出口 --> [*]
E成功出口 --> [*]

@enduml